# Generated by Django 2.2.5 on 2020-05-12 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Planicie', 'Planicie'), ('Ladera', 'Ladera'), ('Cenagoso', 'Cenagoso'), ('Desertico', 'Desertico')], max_length=10)),
                ('area', models.PositiveIntegerField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
